### ISSUE TITLE
Why is this using the keys from openssh in /etc/ssh?

### ISSUE THREAD

**Issue by fvzwieten** [grazzolini/mkinitcpio-dropbear#11]
Because of this there is a dependency with openssh to be installed. Why not use the keys as generated by dropbear itself in /etc/dropbear?

**Comment by fvzwieten** [comment]
Never mind

**Comment by patrakov** [comment]
Using openssh keys is a security issue, and here is why. Note that this is not only my viewpoint, but also how a similar package (https://github.com/dracut-crypt-ssh/dracut-crypt-ssh) in CentOS operates.

Normally, openssh private host keys are on the encrypted LUKS partition, and I am sure that offline attackers (who disassemble my server and image the disk) do not have access to them. But now, with your package installed, they do have access to a copy in the initramfs, and can therefore mount a steealth man-in-the-middle attack against the server at any time. With dedicated initramfs-only keys, they can only access these keys and make a man-in-the-middle attack only against the initramfs.

Of course, with different keys, it is also a good idea to run the ssh server in the initramfs on a non-default port, so that both sets of keys can comfortably sit in the same known_hosts file.
